from PySide6.QtGui import QLinearGradient, QBrush, QPalette, QColor

def set_theme(window):
    if window.is_dark_theme:
        palette = QPalette()
        gradient = QLinearGradient(0, 0, 0, 800)
        gradient.setColorAt(0, QColor("#2A4365"))
        gradient.setColorAt(1, QColor("#1A202C"))
        palette.setBrush(QPalette.Window, QBrush(gradient))
        window.setPalette(palette)
        window.logo.setStyleSheet("color: #E2E8F0; padding: 10px;")
        window.tagline.setStyleSheet("font-size: 14px; color: #A0AEC0; font-style: italic;")
        window.user_input.setStyleSheet("font-size: 14px; padding: 10px; background-color: #2D3748; color: #E2E8F0; border-radius: 8px;")
        window.pin_input.setStyleSheet("font-size: 14px; padding: 10px; background-color: #2D3748; color: #E2E8F0; border-radius: 8px;")
        window.device_combo.setStyleSheet("font-size: 14px; padding: 8px; background-color: #2D3748; color: #E2E8F0; border-radius: 8px;")
        window.command_input.setStyleSheet("font-size: 14px; padding: 10px; background-color: #2D3748; color: #E2E8F0; border-radius: 8px;")
        window.submit_button.setStyleSheet("font-size: 14px; padding: 10px; background-color: #3182CE; color: white; border-radius: 8px;")
        window.loading_label.setStyleSheet("font-size: 14px; color: #A0AEC0; padding: 5px;")
        window.rules_combo.setStyleSheet("font-size: 14px; padding: 8px; background-color: #2D3748; color: #E2E8F0; border-radius: 8px;")
        window.status_label.setStyleSheet("font-size: 14px; color: #A0AEC0;")
        window.status_icon.setStyleSheet("font-size: 14px;")
        window.result_text.setStyleSheet("font-size: 14px; padding: 15px; background-color: #2D3748; color: #E2E8F0; border-radius: 8px;")
        window.history_tree.setStyleSheet("font-size: 12px; padding: 5px; background-color: #2D3748; color: #E2E8F0; border-radius: 8px;")
        window.history_search.setStyleSheet("font-size: 14px; padding: 10px; background-color: #2D3748; color: #E2E8F0; border-radius: 8px;")
        window.manage_users_button.setStyleSheet("font-size: 14px; padding: 10px; background-color: #3182CE; color: white; border-radius: 8px;")
        window.premium_label.setStyleSheet("font-size: 12px; color: #A0AEC0; font-style: italic;")
        window.device_status.setStyleSheet("font-size: 14px; color: #A0AEC0;")
    else:
        palette = QPalette()
        palette.setColor(QPalette.Window, QColor("#FFFFFF"))
        window.setPalette(palette)
        window.logo.setStyleSheet("color: #000000; padding: 10px;")
        window.tagline.setStyleSheet("font-size: 14px; color: #4A4A4A; font-style: italic;")
        window.user_input.setStyleSheet("font-size: 14px; padding: 10px; background-color: #F0F0F0; color: #000000; border: 1px solid #000000; border-radius: 8px;")
        window.pin_input.setStyleSheet("font-size: 14px; padding: 10px; background-color: #F0F0F0; color: #000000; border: 1px solid #000000; border-radius: 8px;")
        window.device_combo.setStyleSheet("font-size: 14px; padding: 8px; background-color: #F0F0F0; color: #000000; border: 1px solid #000000; border-radius: 8px;")
        window.command_input.setStyleSheet("font-size: 14px; padding: 10px; background-color: #F0F0F0; color: #000000; border: 1px solid #000000; border-radius: 8px;")
        window.submit_button.setStyleSheet("font-size: 14px; padding: 10px; background-color: #3182CE; color: white; border: 1px solid #000000; border-radius: 8px;")
        window.loading_label.setStyleSheet("font-size: 14px; color: #4A4A4A; padding: 5px;")
        window.rules_combo.setStyleSheet("font-size: 14px; padding: 8px; background-color: #F0F0F0; color: #000000; border: 1px solid #000000; border-radius: 8px;")
        window.status_label.setStyleSheet("font-size: 14px; color: #4A4A4A;")
        window.status_icon.setStyleSheet("font-size: 14px;")
        window.result_text.setStyleSheet("font-size: 14px; padding: 15px; background-color: #F0F0F0; color: #000000; border: 1px solid #000000; border-radius: 8px;")
        window.history_tree.setStyleSheet("font-size: 12px; padding: 5px; background-color: #F0F0F0; color: #000000; border: 1px solid #000000; border-radius: 8px;")
        window.history_search.setStyleSheet("font-size: 14px; padding: 10px; background-color: #F0F0F0; color: #000000; border: 1px solid #000000; border-radius: 8px;")
        window.manage_users_button.setStyleSheet("font-size: 14px; padding: 10px; background-color: #3182CE; color: white; border: 1px solid #000000; border-radius: 8px;")
        window.premium_label.setStyleSheet("font-size: 12px; color: #4A4A4A; font-style: italic;")
        window.device_status.setStyleSheet("font-size: 14px; color: #4A4A4A;")

def toggle_theme(window):
    window.is_dark_theme = not window.is_dark_theme
    set_theme(window)